---
stages:
  - lint
  - build
  - deploy

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

eslint:
  extends:
    - .default-cache
  stage: lint
  script:
    - npm run lint

prettier:
  extends:
    - .default-cache
  stage: lint
  script:
    - npm run check:format

build:
  extends:
    - .default-cache
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - rsync -a --progress
      --human-readable --delete
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      ./build/* deploy@3.8.204.225:~/realworld/

